import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "SMVI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <head>
        <title>SMVI - Monitoramento de Violência Contra o Idoso</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="bg-gray-100 text-gray-900">
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
